#!/bin/bash
echo "=== API Key Rotation Guide ==="
echo ""
echo "1. DeepSeek API Key:"
echo "   - Login to https://platform.deepseek.com"
echo "   - Go to API Keys section"
echo "   - Create a new key and copy it"
echo "   - Delete/revoke the old key: sk-c4d341a1e691426c9d1264f83274bf69"
echo "   - Update .env.production: DEEPSEEK_API_KEY=<new-key>"
echo ""
echo "2. Stripe Keys:"
echo "   - Login to https://dashboard.stripe.com"
echo "   - Go to Developers > API keys"
echo "   - Roll secrets if compromised"
echo ""
echo "3. After rotation, run: git log --all --full-history -- .env*"
echo "   If the old key appears in history, contact your security team."
echo ""
echo "4. Restart the application: docker compose down && docker compose up -d"
